### ISSUE TITLE
No device connected error on Sequoia 15.0.1

### ISSUE THREAD

**Issue by sgarg26** [cansik/pyrealsense2-macosx#10]
Hey,
I tried running the test depth stream with open-cv that you have provided and I get the no device connected error.
I am running my code with sudo, but that doesn't help either. I'm using a MacBook pro 14 with the m2 pro chip, and device is definitely connected because I can get a video stream going using pure open-cv. Any ideas as to what I can do?
Thanks

**Comment by lkottom** [comment]
I am having the exact same problem. Please let me know if there is a work around or you figure anything out and I will do the same.

**Comment by sgarg26** [comment]
Unfortunately, I don't think this can be fixed. According to #6, it must be fixed by Intel. I also saw cansik make a comment on the official pyrealsense2 repo saying that Mac OS isn't a viable platform for realsense development anymore, and I have switched to a Windows device since then. Hope this helps, and I'm going to close the issue for now.
