### ISSUE TITLE
Access to Infrared Streams through Pyrealsense 2

### ISSUE THREAD

**Issue by danielleamya** [cansik/pyrealsense2-macosx#4]
Hi,

Is there access to the infrared camera streams using this library? When I do a console print-out of all of the available camera feeds, I only see depth and color streams available. When I try to enable and stream infrared frames using the same methods as used to load the depth and color ones my terminal stalls out and nothing appears to be happening.

**Comment by cansik** [comment]
This seems more like a general library problem and not directly connected to the macosx build. I use the infrared stream on a daily bases and it works.

And please provide some more information about your OS, camera model / fw, realsense library, python version and so on.

**Comment by danielleamya** [comment]
Thanks, the issue was on my end as you noted, so I was able to find a solution.
