### ISSUE TITLE
Script sometimes fails to run (Failed power state or timeout): Apple Silicon, Monterey

### ISSUE THREAD

**Issue by danielleamya** [cansik/pyrealsense2-macosx#6]
Hi,
I am attempting to use this library on Monterey with a Mac with the Apple Silicon Chip, and am seeing some issues with the consistency of running scripts including this library and other Realsense application (even with sudo). Whether the scripts will run or not feels completely random. Sometimes the scripts will run with no problem, other times I will see the “failed to set power state” error others have mentioned, or it will completely time out. Any guidance here? I have tested the same script on another Apple Silicon Chip Mac, but running Big Sur and have had no issues with it.

**Comment by cansik** [comment]
Yes, the issue has to be fixed by Intel. This repository just builds pyrealsense2 for macosx, I am not applying any patches.
